### ISSUE TITLE
Display emoji's in text view

### ISSUE THREAD

**Issue by abentele** [abentele/Erbele#19]
see https://github.com/abentele/Fraise/issues/35

**Comment by jawsoftware** [comment]
I don't understand the problem: I correctly see emojis and symbols in text view. Never had problems for this on Fraise/Erbele since El Capitan.

**Comment by abentele** [comment]
Your're right. With current version of Erbele (3.8.5) on macOS Catalina this isn't an issue.
Therefore I close this issue.

**Comment by jawsoftware** [comment]
Hi Andreas,

did you managed to give a look to my pull request?
