### ISSUE TITLE
Error loading macOS 10.12 Sierra

### ISSUE THREAD

**Issue by jericane1** [abentele/Erbele#28]
Hello,

I use a Mac OS X 10.12 and a Mac OS X 10.11 with Hackintosh (Asus P5E3 Premium + Intel Core 2 Quad Q9450).
With Mac OS X 10.11, I use Fraise (jfmoy), without any problem: everything works.
With Mac OS X 10.12, supports Fraise (abentele).
I open the first time Strawberry (abentele), it launches without problem. I close it. And then a crash prevents me from throwing it. And here are 2 different crashes :
[KP-1012.txt](https://github.com/abentele/Erbele/files/763194/KP-1012.txt)
[KP-1012b.txt](https://github.com/abentele/Erbele/files/763195/KP-1012b.txt)
jericane1

**Comment by abentele** [comment]
fixed in release 3.8; please check out: https://github.com/abentele/Erbele/releases/tag/3.8
