### ISSUE TITLE
feature request: timestamp and pinned files and more

### ISSUE THREAD

**Issue by reclaimed** [abentele/Erbele#32]
hello there. thank you for the great effort. please consider the features to add:
- microsoft notepad.exe has an undocumented but useful feature: if you place the special token ".LOG" at the very beginning of a text file, when you open the file the notepad jumps to the end and inserts the timestamp. useful for diaries and notes
- a way to pin a file to the sidebar to make sure it won't go away if you accidentally close it
- select the invisible characters to be shown. say, tabs, BOM, CR, and LF are nice to see, but having the "visible" spaces is a bit irritating

**Comment by abentele** [comment]
sorry for late response to this ticket.

I want to leave some comments on it:

* ".LOG" feature: this is a very special feature, and I think it isn't something which many users would use. I think the macOS way would be to automate things with automator / scripts.
* there is already an option to create projects in Erbele. If you accidentally close a file, simply reopen it with File > Used documents. A related ticket ist #51.
* select invisible characters to be shown: I think this is an acceptable feature request. I create a new ticket for this, to have one ticket per feature: #52.

Therefore I close this duplicate ticket.
