### ISSUE TITLE
Is a Windows version possible?

### ISSUE THREAD

**Issue by Marc66** [abentele/Erbele#35]
I'm a happy user of Erbele on my home Mac and I'm struggling to find an equivalent for Windows. I used Notepad++ for many years but recent changes made me drop it. I am currently using [Kate](https://kate-editor.org/) and also tried Gedit, Komodo and PSPad but none of them have the flexibility and simplicity of Erbele.

Is is possible to take the exisitng source code and compile it on Windows? If not, what changes would be required and would it be complex to do? I wouldn't mind trying but I haven't programmed or compiled in many years.

I am using a few applications on both my work PC and home machine, so something is certainly possible. For example, the following Apps are available both as MacOS and Windows versions: Kate, Veracrypt, Gimp, Gedit, Komodo, VLC, ...

Thank you

**Comment by abentele** [comment]
Erbele isn't designed to be ported to Windows. It's programmed in Objective-C and the macOS Cocoa library, so it's a platform dependent macOS application. Positively spoken, platform dependent macOS apps normally have a better user experience than applications that run both on the Mac and Windows. There are definitely no plans to create a port of Erbele for Windows.

Although I don't want this issue tracker to be a forum to discuss alternatives, I would propose Visual Studio Code or Atom as a good alternative for Windows (and also the Mac).

**Comment by rkarolak** [comment]
On Windows, for a lightweight program I like to use is Notepad2 (Notepad2-mod for an updated fork). It has a good array of features and is still fairly minimal in its interface. It can be customized and there are some forks that provide more features, like tabs and cold folding. I recommend checking that out if these are some things you like about Erbele. The original Scite editor is also highly customizable, but takes more effort to do so as most of this is done by editing configuration files.

For something more heavyweight I second Visual Studio Code. It's customizable and has a lot of community support for plugins.
