### ISSUE TITLE
Erbele

### ISSUE THREAD

**Issue by fazlihon** [abentele/Erbele#36]
how to install Erbele SOFTWARE on Sierra?

**Comment by abentele** [comment]
please provide a complete issue description:
- what did you try?
- what was the problem?

**Comment by fazlihon** [comment]
Opened the archive in the folder applications. How to install correctly?

**Comment by abentele** [comment]
did you use the Erbele_3.8.4.dmg archive?
Open it, and copy the Erbele.app to the applications folder, as you would do with any other program on the Mac.
Is there any specific issue with Sierra?

**Comment by fazlihon** [comment]
i downloaded on the site this archive: Erbele-master.zip
There is no Erbele.app in the archive

**Comment by abentele** [comment]
I've already answered the question. You don't provide additional aspects, so I assume there is no issue with Erbele on Sierra. So I close the issue.

**Comment by fazlihon** [comment]
Where can I get Erbele_3.8.4.dmg?

**Comment by abentele** [comment]
https://github.com/abentele/Erbele/releases

**Comment by fazlihon** [comment]
Happened! Thank you so much for the help!)
