### ISSUE TITLE
Crash with 3.10

### ISSUE THREAD

**Issue by hassaniriad** [abentele/Erbele#50]
First of all, thank you very much for this great and useful application that I have been using for several years.

Until now I was using version 3.8 but due to some problems I upgraded to 3.10. However, when I open a new document with Erbele, the application crashes as soon as I start to enter text in the editor.

I'm on mac 10.14.6 (Mojave) and I'm attaching the problem report.
Maybe you have an idea or some hints?
[report.txt](https://github.com/abentele/Erbele/files/6796893/report.txt)

**Comment by abentele** [comment]
Unfortunately I cannot reproduce this bug on macOS Big Sur. I don't have any Mac with Mojave to reproduce it. Therefore I cannot support Erbele on older macOS versions.

After having searched the Internet for this bug, it seems to be a macOS bug, not a bug in the application.

What I can do for you: if you try all the versions between 3.8 and 3.10 and tell me which work for you and which not, I maybe can find the change better which may have introduced this problem. If you are familiar with git and Xcode, try to find the commit which introduced the problem by yourself, and tell me which commit.

**Comment by hassaniriad** [comment]
Thank you Andreas for considering my problem. Yes you are right, this problem does not seem to be caused by Erbele: all versions have the same behavior and moreover (and very interesting), when I log in on my laptop under another user account, everything works perfectly! so I suspect a problem with my configuration.  
I still have to find out what (I don't remember having done any recent update).

**Comment by abentele** [comment]
closed because not reproducible. Please open another ticket if you have more detailed information based on current Erbele version.
