### ISSUE TITLE
Scroll freezes

### ISSUE THREAD

**Issue by Marc66** [abentele/Erbele#53]
Since the last version, whenever I scroll (with the virtual mouse wheel) inside a text file with more than 100 lines, scroll gets stuck. I need to use the elevators to move past line 100. This happens in both directions:
- If I am at the start of the file and scroll down, it gets stuck at around line 100 
- If I am after line 100 and scroll up, it also gets stuck at around line 100

It does not always happen with all files but it happens often enough to bother me.

Can you please look into this?

Running latest Erbele from MAS on latest Big Sur

**Comment by abentele** [comment]
Thanks for this bug report.
Can reproduce it.
Bug introduced with commit ed7ef6ab35489bd704c31f1dea8dbba984dc2200.

I have to investigate on it.

**Comment by abentele** [comment]
will be fixed in release 4.0.2 which is now uploaded to App Store Connect for review by Apple. It will be available in App Store after < 48h. Please report if the problems are fixed in your opinion, or not.
