### ISSUE TITLE
Inline commands don't work

### ISSUE THREAD

**Issue by abentele** [abentele/Erbele#56]
e.g. Tools > Commands > Other > "Insert current date"

does nothing...

**Comment by fbonaldi** [comment]
Dear Andreas,

I used to use Erbele to launch FreeFEM scripts (https://freefem.org/), i.e., EDP files, but now it no longer works. When I run a script, it should open the Terminal, but it does not.
The command is very similar to that I used with Fraise, i.e.,

**/Applications/FreeFem++.app/Contents/ff-4.12/bin/FreeFem++-CoCoa %%p**

If I do not run the script from Erbele, but I do it by copying and pasting the sequence directly in the Terminal, it works.

Thanks for your help!

Francesco

**Comment by abentele** [comment]
related to original issue description: fixed in Release 6.1.

@fbonaldi Please await the new release 6.1 in App Store (should be available tomorrow) and check it out.
If it's not fixed for you, then it's maybe another issue. Therefore please report another issue in github, with some more details (e.g. screencast/video). Btw.: I could not install FreeFem++ on my Mac M2 Pro with macOS Ventura, therefore I cannot test it. Can you describe excactly how the behavior was in Fraise (which OS version)?
